---
- name: Umee git checkout
  ansible.builtin.git:
    repo: "{{ umeed_github_uri }}"
    dest: "{{ umeed_src }}"
    version: "{{ umeed_version }}"

- name: Build umee daemon executable
  make:
    chdir: "{{ umeed_src }}"
    target: install
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_local['golang']['general']['home'] }}/bin"
    GOPATH: "{{ ansible_env.HOME }}/work"
