---
- name: Init umee node
  command: "umeed init {{ moniker }} --chain-id {{ chain_id }} -o"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/work"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_local['golang']['general']['home'] }}/bin:{{ ansible_env.HOME }}/work/bin"

- name: Download and ensure file integrity
  get_url:
    url: "{{ umeed_genesis }}"
    dest: "{{ umeed_home_dir}}/config/genesis.json"
    checksum: "sha256:{{ umeed_genesis_checksum }}"

- name: Add chain seeds
  ansible.builtin.lineinfile:
    path: "{{ umeed_home_dir}}/config/config.toml"
    regexp: '^.*seeds ?= ?"'
    line: 'seeds = "{{ umeed_seeds | join(",") }}"'

- name: Add chain persistent peers
  ansible.builtin.lineinfile:
    path: "{{ umeed_home_dir}}/config/config.toml"
    regexp: '^.*persistent_peers ?= ?"'
    line: 'persistent_peers = "{{ umeed_persistent_peers | join(",") }}"'

- name: Set JSON logs
  ansible.builtin.lineinfile:
    path: "{{ umeed_home_dir}}/config/config.toml"
    regexp: '^.*log_format ?= ?"'
    line: 'log_format = "json"'

- name: Activate prometheus metrics
  ansible.builtin.lineinfile:
    path: "{{ umeed_home_dir}}/config/config.toml"
    regexp: "^.*prometheus = false"
    line: "prometheus = true"
